"""yes

Revision ID: 058e24eb23ad
Revises: 
Create Date: 2026-09-22 15:19:43.606462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '058e24eb23ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_table',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('from_a', sa.Enum('CHECKING', 'SAVING', name='accounttype', native_enum=False), nullable=False),
    sa.Column('type', sa.Enum('WIRE_TRANSFER', 'LOCAL_TRANSFER', 'INTERNAL_TRANSFER', name='transfertype', native_enum=False), nullable=False),
    sa.Column('beneficiary_account', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('beneficiary_name', sa.String(length=255), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=False),
    sa.Column('swift_code', sa.String(length=100), nullable=True),
    sa.Column('routing_number', sa.String(length=100), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('pin', sa.String(length=255), nullable=False),
    sa.Column('bank_address', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('chat_rooms',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', name='chatstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_table('chat_messages',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('chat_room_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('sender_type', sa.Enum('ADMIN', 'CUSTOMER', name='role', native_enum=False), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_room_id'], ['chat_rooms.room_id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_messages')
    op.drop_table('chat_rooms')
    op.drop_table('transaction_table')
    # ### end Alembic commands ###
