"""yes

Revision ID: 07c54f49729b
Revises: 19d1efdd0828
Create Date: 2026-09-26 16:20:53.630968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '07c54f49729b'
down_revision: Union[str, Sequence[str], None] = '19d1efdd0828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_ibfk_1'), 'users', type_='foreignkey')
    op.drop_column('users', 'account_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('users_ibfk_1'), 'users', 'account', ['account_id'], ['account_id'])
    # ### end Alembic commands ###
