"""yes

Revision ID: 19d1efdd0828
Revises: e22678325bab
Create Date: 2026-09-26 15:56:55.411763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19d1efdd0828'
down_revision: Union[str, Sequence[str], None] = 'e22678325bab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'account', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_column('account', 'user_id')
    # ### end Alembic commands ###
