"""ys

Revision ID: 1d867022ca24
Revises: 75bc6380d18c
Create Date: 2026-10-01 11:03:27.833382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1d867022ca24'
down_revision: Union[str, Sequence[str], None] = '75bc6380d18c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_rooms', 'status',
               existing_type=mysql.VARCHAR(length=6),
               type_=sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='chatstatus', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_rooms', 'status',
               existing_type=sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='chatstatus', native_enum=False),
               type_=mysql.VARCHAR(length=6),
               existing_nullable=False)
    # ### end Alembic commands ###
