""" add refernce_id to table

Revision ID: 212818513ad6
Revises: 385be9d26b3e
Create Date: 2026-09-29 04:08:23.931693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '212818513ad6'
down_revision: Union[str, Sequence[str], None] = '385be9d26b3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_table', sa.Column('reference_id', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'transaction_table', ['reference_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction_table', type_='unique')
    op.drop_column('transaction_table', 'reference_id')
    # ### end Alembic commands ###
