""" add fee and status table

Revision ID: 408d8a9ae946
Revises: f15720dceb2a
Create Date: 2026-09-29 03:56:48.982851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '408d8a9ae946'
down_revision: Union[str, Sequence[str], None] = 'f15720dceb2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_table', sa.Column('fee', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('transaction_table', sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='status', native_enum=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_table', 'status')
    op.drop_column('transaction_table', 'fee')
    # ### end Alembic commands ###
