"""edit model

Revision ID: 4b976de68030
Revises: 5810e730f0bb
Create Date: 2026-09-29 15:31:24.993690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4b976de68030'
down_revision: Union[str, Sequence[str], None] = '5810e730f0bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction_table', 'from_a',
               existing_type=mysql.VARCHAR(length=8),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction_table', 'from_a',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###
