"""yes

Revision ID: 5810e730f0bb
Revises: a6230bc294a7
Create Date: 2026-09-29 05:34:15.992433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5810e730f0bb'
down_revision: Union[str, Sequence[str], None] = 'a6230bc294a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_table', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'transaction_table', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction_table', type_='foreignkey')
    op.drop_column('transaction_table', 'user_id')
    # ### end Alembic commands ###
