"""yes

Revision ID: d665cce9807a
Revises: 1d867022ca24
Create Date: 2026-10-02 08:11:10.299278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd665cce9807a'
down_revision: Union[str, Sequence[str], None] = '1d867022ca24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('status', sa.Enum('ACTIVE', 'FREEZE', 'RESTRICTED', name='accountstatus', native_enum=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'status')
    # ### end Alembic commands ###
